"""initial tables

Revision ID: d3de5502634c
Revises: 
Create Date: 2026-03-26 13:27:31.469095

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3de5502634c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False, comment='Logical reference to payments.id.NO FK constraint by design - audit rows must survive payment deletion '),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='eg INITIATED, DARAJA_ACCEPTED, CALLBACK_RECEIVED, COMPLETED, FAILED'),
    sa.Column('actor', sa.String(length=100), nullable=False, comment="Who triggered the event : 'api_user', 'daraja_callback', 'celery_worker'"),
    sa.Column('payload_json', sa.Text(), nullable=True, comment='Sanitised, JSON-encoded event context. PII stripped before storage. NULL only for events with no meaningful context.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='X-Request-id/trace ID for cross-service trace correlation'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA-256 of (payment_id|event_type|payload_json|previous_checksum).Recompute and compare to detect row tampering.'),
    sa.Column('previous_checksum', sa.String(length=64), nullable=True, comment='Checksum of the previous audit row for this payment_id. NULL only for the first event of a payment. Forms a linked hash chain — breaking any link indicates tampering.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created_at', 'payment_audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_event_type', 'payment_audit_log', ['event_type'], unique=False)
    op.create_index('ix_audit_payment_id', 'payment_audit_log', ['payment_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID V4 primary key,generated application-side for traceability before DB write.'),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False, comment='Normalised MSISDN: 2547XXXXXXXX. Never store raw user input.'),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('account_reference', sa.String(length=12), nullable=False, comment="Appears on customer's M-Pesa confirmation SMS."),
    sa.Column('transaction_desc', sa.String(length=13), nullable=False, comment='Human-readable payment description sent to Daraja.'),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False, comment='Client-suplied dedup key. UNIQUE enforced at DB level'),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True, comment='Daraja CheckoutRequestID. USed to match inbound callbacks'),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt', sa.String(length=20), nullable=True, comment='MPESA trans receipt(e.g QWRTTHGGBV). Unique per transaction'),
    sa.Column('amount_paid', sa.Numeric(precision=19, scale=4), nullable=True, comment='Actual amount confirmed by M-PESA.May differ form amount if customer modifeid value. NULL until COMPLETED status '),
    sa.Column('mpesa_transaction_date', sa.DateTime(timezone=True), nullable=True, comment="Daraja TransactionDate: YYYYMMDDHHmmss (UTC+3 / Nairobi time). Stored as UTC. Parse with: datetime.strptime(raw, '%Y%m%d%H%M%S')."),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=True, comment='Daraja ResultCode from callback.0=sucess other indicate failure type'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.CheckConstraint('amount_paid IS NULL OR amount_paid >0', name='ck_payments_amount_paid_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_payments_checkout_request_id', 'payments', ['checkout_request_id'], unique=False)
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_mpesa_receipt', 'payments', ['mpesa_receipt'], unique=False)
    op.create_index('ix_payments_phone', 'payments', ['phone'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_created_at', 'payments', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status_created_at', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_phone', table_name='payments')
    op.drop_index('ix_payments_mpesa_receipt', table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_index('ix_payments_checkout_request_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_audit_payment_id', table_name='payment_audit_log')
    op.drop_index('ix_audit_event_type', table_name='payment_audit_log')
    op.drop_index('ix_audit_created_at', table_name='payment_audit_log')
    op.drop_table('payment_audit_log')
    # ### end Alembic commands ###
